# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/HTML.gitlab-ci.yml

# Full project: https://gitlab.com/pages/plain-html
pages:
  image: node:22-alpine3.19
  stage: deploy
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never # Don't run for other branches
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - duckduckhacks/node_modules/
  script:
    #build React project for record-hacks and duckhacks
    - cd hackhackgoose
    - npm install
    - npm run build
    - cd ..

    - mkdir .public
    - cp -r ./* .public
    - cp -r hackhackgoose/dist .public/hackhackgoose
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
      - public
